
services:
  database:
    image: postgres:15.8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cloudsqliamuser
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: default_database
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local