name: bidrag-automatisk-jobb
ingresses:
  - https://bidrag-automatisk-jobb.intern.nav.no
limits:
  cpu: 1000m
  memory: 2048Mi
requests:
  cpu: 500m
  memory: 2000Mi
replicas:
  max: 2
  min: 2
database:
  navn: bidrag-automatisk-jobb-prod
  tier: db-custom-1-3840
  size: 25
kafka:
  pool: nav-prod
env:
  PERSON_URL: https://bidrag-person.prod-fss-pub.nais.io/bidrag-person
  PERSON_SCOPE: prod-fss.bidrag.bidrag-person-feature
  PERSON_HOST: bidrag-person.prod-fss-pub.nais.io
  KAFKA_VEDTAK_TOPIC: bidrag.vedtak
  KAFKA_PERSON_HENDELSE_TOPIC: bidrag.personhendelse.v1
  JAVA_OPTS: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:MaxRAMPercentage=80.0
