apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: bidrag-automatisk-jobb
  namespace: bidrag
  labels:
    team: bidrag
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: bidrag
  secretName: {{unleash.secret_name}}
  environment: {{unleash.env}}