management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"

springdoc:
  packages-to-scan: no.nav.bidrag.aldersjustering.controller
spring.main.banner-mode: off
---
spring.config.activate.on-profile: nais,lokal-nais

no.nav.security.jwt:
  client:
    registration:
      bidrag-person:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_post
  issuer.aad:
    discovery_url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/v2.0/.well-known/openid-configuration
    accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

spring:
  datasource:
    url: ${DB_JDBC_URL}
    hikari:
      idle-timeout: 10001
      max-lifetime: 30001
      connectionTimeout: 1000
      maximum-pool-size: 10
      minimum-idle: 1
      data-source-properties:
        ssl: true
        sslmode: ${DB_SSLMODE}
        sslcert: ${DB_SSLCERT}
        sslkey: ${DB_SSLKEY_PK8}
        sslrootcert: ${DB_SSLROOTCERT}
  flyway:
    enabled: true
    locations: classpath:/db/migration
  jpa:
    database: postgresql
    open-in-view: false
