name: Deploy Q4
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'
  push:
    branches:
      - '**'
      - '!main'
      - '!q1/**'
      - '!Q1/**'
      - '!q2/**'
      - '!Q2/**'

jobs:
  build_and_deploy:
    name: "Build and deploy to Q4"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      nais_variabler_filnavn: q4.yaml

  deploy_unleash:
    runs-on: ubuntu-latest
    name: Deploy unleash

    steps:
      - uses: actions/checkout@v4
      - name: Deploy unleash to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/unleash.yaml
          VARS: .nais/q4.yaml